### ISSUE TITLE
ubuntu18.04编译问题

### ISSUE THREAD

**Issue by snowflake119** [calibtoolkit/calibration_kit#8]
[](url)1. - [ ] 在下载代码到本地后,按照readme操作
ubuntu18.04 g++版本无法升级到9.0及以上
g++版本8.4
clang 9.0
cmake 3.19
编译无法继续
执行命令如下:cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug 
[错误如下]:

CMake Error at /usr/local/share/cmake-3.19/Modules/ExternalProject.cmake:2748 (message):
  No download info given for 'ftxui-populate' and its source directory:

   /home/maxus/calibration_kit-main/build/_deps/ftxui-src

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/ExternalProject.cmake:3430 (_ep_add_download_command)
  CMakeLists.txt:13 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/maxus/calibration_kit-main/build/_deps/ftxui-subbuild/CMakeFiles/CMakeOutput.log".

CMake Error at /usr/local/share/cmake-3.19/Modules/FetchContent.cmake:977 (message):
  CMake step for ftxui failed: 1
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FetchContent.cmake:1111:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.19/Modules/FetchContent.cmake:1111 (cmake_language)
  CMakeLists.txt:18 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!
请问ubuntu18.04下好编译过吗?

**Comment by snowflake119** [comment]
[ 11%] Performing download step (git clone) for 'ftxui-populate'
正克隆到 'ftxui-src'...
fatal: unable to access 'https://github.com/ArthurSonzogni/ftxui/': Could not resolve proxy: http
正克隆到 'ftxui-src'...
fatal: unable to access 'https://github.com/ArthurSonzogni/ftxui/': Could not resolve proxy: http
正克隆到 'ftxui-src'...
fatal: unable to access 'https://github.com/ArthurSonzogni/ftxui/': Could not resolve proxy: http
-- Had to git clone more than once:
          3 times.
CMake Error at ftxui-subbuild/ftxui-populate-prefix/tmp/ftxui-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/ArthurSonzogni/ftxui'


CMakeFiles/ftxui-populate.dir/build.make:114: recipe for target 'ftxui-populate-prefix/src/ftxui-populate-stamp/ftxui-populate-download' failed
make[2]: *** [ftxui-populate-prefix/src/ftxui-populate-stamp/ftxui-populate-download] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/ftxui-populate.dir/all' failed
make[1]: *** [CMakeFiles/ftxui-populate.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

CMake Error at /usr/local/share/cmake-3.19/Modules/FetchContent.cmake:989 (message):
  Build step for ftxui failed: 2
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FetchContent.cmake:1111:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.19/Modules/FetchContent.cmake:1111 (cmake_language)
  CMakeLists.txt:18 (FetchContent_Populate)


-- Configuring incomplete, errors occurred!
更正后,又出现这个错误

**Comment by incloon** [comment]
此问题是由于网络原因导致的，cmake中使用了超级构建来在配置期下载FTXUI依赖，需要连接github，但是你的网络似乎访问github存在一些问题，未能成功下载，目前暂不支持手动安装FTXUI
当 #7 修复之后将会支持手动安装FTXUI
