### ISSUE TITLE
ubuntu 18.04链接问题

### ISSUE THREAD

**Issue by snowflake119** [calibtoolkit/calibration_kit#9]
[ 97%] Built target camera_model
Scanning dependencies of target calibration_kit
[ 97%] Building CXX object CMakeFiles/calibration_kit.dir/src/main.cpp.o
[ 97%] Building CXX object CMakeFiles/calibration_kit.dir/src/nonlinear_optimization_demo.cpp.o
[100%] Linking CXX executable calibration_kit
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::path::path(std::filesystem::__cxx11::path&&)’中：
/usr/include/c++/8/bits/fs_path.h:172：对‘std::filesystem::__cxx11::path::_M_split_cmpts()’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::path::clear()’中：
/usr/include/c++/8/bits/fs_path.h:310：对‘std::filesystem::__cxx11::path::_M_split_cmpts()’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::operator==(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)’中：
/usr/include/c++/8/bits/fs_path.h:546：对‘std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::path::operator+=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
/usr/include/c++/8/bits/fs_path.h:821：对‘std::filesystem::__cxx11::path::_M_split_cmpts()’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::directory_entry::status() const’中：
/usr/include/c++/8/bits/fs_dir.h:260：对‘std::filesystem::status(std::filesystem::__cxx11::path const&)’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&)’中：
/usr/include/c++/8/bits/fs_dir.h:361：对‘std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::directory_iterator::operator->() const’中：
/usr/include/c++/8/bits/fs_dir.h:386：对‘std::filesystem::__cxx11::directory_iterator::operator*() const’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::exists(std::filesystem::__cxx11::path const&)’中：
/usr/include/c++/8/bits/fs_ops.h:121：对‘std::filesystem::status(std::filesystem::__cxx11::path const&)’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::is_directory(std::filesystem::__cxx11::path const&)’中：
/usr/include/c++/8/bits/fs_ops.h:171：对‘std::filesystem::status(std::filesystem::__cxx11::path const&)’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘IOFilesystemBase::IOFilesystemBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)::{lambda()#1}::operator()() const’中：
/home/maxus/calibration_kit/src/tui_tools.h:169：对‘std::filesystem::__cxx11::path::root_path() const’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘IOFilesystemBase::IOFilesystemBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)’中：
/home/maxus/calibration_kit/src/tui_tools.h:159：对‘std::filesystem::__cxx11::path::parent_path() const’未定义的引用
/home/maxus/calibration_kit/src/tui_tools.h:163：对‘std::filesystem::current_path[abi:cxx11]()’未定义的引用
/home/maxus/calibration_kit/src/tui_tools.h:166：对‘std::filesystem::__cxx11::path::parent_path() const’未定义的引用
/home/maxus/calibration_kit/src/tui_tools.h:166：对‘std::filesystem::__cxx11::path::parent_path() const’未定义的引用
/home/maxus/calibration_kit/src/tui_tools.h:166：对‘std::filesystem::__cxx11::path::parent_path() const’未定义的引用
/home/maxus/calibration_kit/src/tui_tools.h:173：对‘std::filesystem::__cxx11::path::root_path() const’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘IOFilesystemBase::findFile()’中：
/home/maxus/calibration_kit/src/tui_tools.h:192：对‘std::filesystem::__cxx11::directory_iterator::operator*() const’未定义的引用
/home/maxus/calibration_kit/src/tui_tools.h:192：对‘std::filesystem::__cxx11::directory_iterator::operator++()’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘Camera::calibration()’中：
/home/maxus/calibration_kit/src/main.cpp:199：对‘std::filesystem::__cxx11::directory_iterator::operator++()’未定义的引用
CMakeFiles/calibration_kit.dir/src/main.cpp.o：在函数‘std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)’中：
/usr/include/c++/8/bits/fs_path.h:185：对‘std::filesystem::__cxx11::path::_M_split_cmpts()’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/calibration_kit.dir/build.make:726: recipe for target 'calibration_kit' failed
make[2]: *** [calibration_kit] Error 1
CMakeFiles/Makefile2:406: recipe for target 'CMakeFiles/calibration_kit.dir/all' failed
make[1]: *** [CMakeFiles/calibration_kit.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2
ubuntu18.04编译到最后提示链接问题,提示未定义的引用,好像是库链接的问题,请教下这个问题何解?

**Comment by snowflake119** [comment]
是不是因为个++版本不对啊,因为目前我的是ubuntu18.04,尝试按照readme升级g++版本,但最多升级到8.4,无法再升级到更高版本了,所以请教下这个问题怎么解决?

**Comment by incloon** [comment]
使用g++8-g++9.1版本会有链接filesystem问题，你可以在顶层CMakeLists.txt的53行添加stdc++fs解决此问题
